### ISSUE TITLE
ERR: pngdefry : seen 1 file(s), wrote 0 file(s) fs.js:640

### ISSUE THREAD

**Issue by litt1e-p** [bumaociyuan/ios-ipa-server#11]
@bumaociyuan hi, I get an error below:
```
pngdefry : seen 1 file(s), wrote 0 file(s)
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
...
```
and my install steps:
```
git clone https://github.com/bumaociyuan/ios-ipa-server.git
cd ios-ipa-server
npm install 
npm link
ios-ipa-server
```
and I also modify the template.plist with my app identifier(same as .ipa's name)
at last, it crashed after visited `https://my_local_ip:1234/download`
please do some help when your are free, thanks!

**Comment by bumaociyuan** [comment]
Thank you for report this
I'll check this on Monday

**Comment by bumaociyuan** [comment]
```
git clone https://github.com/bumaociyuan/ios-ipa-server.git
cd ios-ipa-server
npm install 
npm link
cd ipa-folder/
ios-ipa-server
```

On my mac everything works fine.

Would you post your system version and
```
node --version
npm --version
```

**Comment by litt1e-p** [comment]
@bumaociyuan node: v6.6.0, npm: 3.10.7, my verbose:
```
$ ios-ipa-server
https://192.168.2.133:1234/download
./icon.png : not an -iphone crushed PNG file
pngdefry : seen 1 file(s), wrote 0 file(s)
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './icon_tmp.png'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at base64_encode (/Users/mac/Desktop/ipa-automic/ios-ipa-server/bin/ios-ipa-server.js:207:19)
    at /Users/mac/Desktop/ipa-automic/ios-ipa-server/bin/ios-ipa-server.js:189:49
    at Array.forEach (native)
    at itemInfoWithName (/Users/mac/Desktop/ipa-automic/ios-ipa-server/bin/ios-ipa-server.js:183:14)
    at /Users/mac/Desktop/ipa-automic/ios-ipa-server/bin/ios-ipa-server.js:124:20
    at /Users/mac/Desktop/ipa-automic/ios-ipa-server/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by bumaociyuan** [comment]
I just quick fixed this bug
```
cd ios-ipa-server-repo/
git pull
cd ipa-location/
ios-ipa-server # try again
```

**Comment by litt1e-p** [comment]
@bumaociyuan yeah! It works now after I `git pull` and `git checkout templates/template.plist` and delete the same bundleIdentifier app,  now it still shows some error but app can be installed:
```
$ ios-ipa-server
https://192.168.2.133:1234/download
./icon.png : not an -iphone crushed PNG file
pngdefry : seen 1 file(s), wrote 0 file(s)
{ Error: ENOENT: no such file or directory, open './icon_tmp.png'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at base64_encode (/Users/mac/Desktop/ipa-automic/ios-ipa-server-lib/bin/ios-ipa-server.js:214:19)
    at /Users/mac/Desktop/ipa-automic/ios-ipa-server-lib/bin/ios-ipa-server.js:193:51
    at Array.forEach (native)
    at itemInfoWithName (/Users/mac/Desktop/ipa-automic/ios-ipa-server-lib/bin/ios-ipa-server.js:187:16)
    at /Users/mac/Desktop/ipa-automic/ios-ipa-server-lib/bin/ios-ipa-server.js:125:20
    at /Users/mac/Desktop/ipa-automic/ios-ipa-server-lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './icon_tmp.png' }
./icon.png : writing to file ./icon_tmp.png
pngdefry : seen 1 file(s), wrote 1 file(s)
```

**Comment by bumaociyuan** [comment]
@litt1e-p It's just a quick fix. I print the error log. Just ignore that.

**Comment by litt1e-p** [comment]
@bumaociyuan all right, thank you

**Comment by zhao0** [comment]
@litt1e-p It looks like that there are some problem with your app's icon, make sure it is a iphone crushed PNG file

**Comment by litt1e-p** [comment]
@bumaociyuan I archived two ipa file which one was archive by Xcode and other one archived by [shenzhen](https://github.com/nomad/shenzhen) tools(this ipa caused the error), so it is not `ios-ipa-server`'s fault, you are right, I will fix it myself. thanks a lot!
