### ISSUE TITLE
Mac 点击安装就出错了，用npm安装的

### ISSUE THREAD

**Issue by hello--world** [bumaociyuan/ios-ipa-server#16]
_http_outgoing.js:555
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:555:11)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:110:11)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at /usr/local/lib/node_modules/ios-ipa-server/node_modules/graceful-fs/graceful-fs.js:190:14
    at /usr/local/lib/node_modules/ios-ipa-server/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:123:15)

node --version 
v6.9.1
npm --version
4.0.3

**Comment by bumaociyuan** [comment]
`npm install -g ios-ipa-server` 是这样安装的吗？

**Comment by hello--world** [comment]
是我测试时把目录给改了。。。现在好了。只不过目录带“HelloWorld 2016-11-18 16-00-48”的字符会出错。
