### ISSUE TITLE
TypeError: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by aichy6666** [bumaociyuan/ios-ipa-server#22]
/etc/rc.local 下增加开机启动任务
/usr/bin/ios-ipa-server /home/pi/api
日志记录到/var/log下
`TypeError: Cannot read property 'address' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:46:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3`
会报错

**Comment by bumaociyuan** [comment]
@aichy6666 你是什么系统?
简单的解决办法 `/etc/rc.local` 下增加开机启动任务
 `/usr/bin/ios-ipa-server /home/pi/api -i  <your-ip>`

**Comment by aichy6666** [comment]
谢谢我试一试  树莓派B3 Debian
