### ISSUE TITLE
运行ios-ipa-server时报错

### ISSUE THREAD

**Issue by dxGuan** [bumaociyuan/ios-ipa-server#25]
运行ios-ipa-server /home/webedit/ios-ipa/后
报错：
/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:50
var globalCerFolder = os.homedir() + '/.ios-ipa-server/' + ipAddress;
                         ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:50:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
webedit@wab-test:~$ sudo ios-ipa-server ./ios-ipa/

/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:50
var globalCerFolder = os.homedir() + '/.ios-ipa-server/' + ipAddress;
                         ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:50:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by bumaociyuan** [comment]
@dxGuan 更新1.1.5 已修复此bug
