### ISSUE TITLE
我的ipa总是下载失败

### ISSUE THREAD

**Issue by WCrazyStone** [bumaociyuan/ios-ipa-server#4]
安装的方式：$ npm install -g ios-ipa-server

安装成功后：这个目录下面存放的SSL的证书  /Users/crccc/.ios-ipa-server/14.16.9.7/

在plist文件中

<dict>
	<key>kind</key>
	<string>software-package</string>

	<key>url</key>
        <string>https://{{ip}}:{{port}}/ipa/{{name}}.ipa</string>
</dict>

我不是很明白的：https://{{ip}}:{{port}}/ipa/{{name}}.ipa 这个URL

请问，这个URL是代表服务器端ipa存放的路径？但是感觉不像啊？

还有就是我把代码下载下来之后，添加了一些log输出，怎么重新运行？

**Comment by WCrazyStone** [comment]
./ios-ipa-server.js 

module.js:327
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/crcc/Desktop/ios-ipa-server/bin/ios-ipa-server.js:3:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by bumaociyuan** [comment]
@WCrazyStone 

```
git clone git@github.com:bumaociyuan/ios-ipa-server.git
cd ios-ipa-server

# 安装依赖包
npm install 

# 建立link 方便调试
npm link

# 运行服务
node bin/ios-ipa-server.js 

# 或者 在有ipa的文件夹下
ios-ipa-server
```

**Comment by WCrazyStone** [comment]
多谢哈，之前下载失败的原因，是因为我用$ npm install -g ios-ipa-server安装之后，我没有修改templtes 文件夹下面的 plist文件中的bundle-identifier。修改之后，就可以安装成功了。

但是我很有疑惑的如下：
在plist文件中，URL的值：

<key>url</key>
<string>https://{{ip}}:{{port}}/ipa/{{name}}.ipa</string>

在 https://{{ip}}:{{port}}/ipa/{{name}}.ipa  URL中，

https://{{ip}}:{{port}}/指的是服务器的地址，ipa/{{name}}.ipa 可以理解成服务器上   ipa文件夹下面 的ipa文件么？

但是这样理解也不对？

该怎么理解呢？

**Comment by bumaociyuan** [comment]
@WCrazyStone 可以这样理解
