### ISSUE TITLE
当我在vps上部署的时候失败了，以下是报错信息，我想通过外网访问

### ISSUE THREAD

**Issue by phpmaple** [bumaociyuan/ios-ipa-server#5]
/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:31
var globalCerFolder = os.homedir() + '/.ios-ipa-server/' + ipAddress;
                         ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (/usr/local/lib/node_modules/ios-ipa-server/bin/ios-ipa-server.js:31:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by bumaociyuan** [comment]
@phpmaple 你是用root 用户登录的吗？

**Comment by phpmaple** [comment]
@bumaociyuan node版本的问题解决了可以访问但是网页没有显示app的icon

**Comment by bumaociyuan** [comment]
@phpmaple linux 暂时不支持显示icon

**Comment by phpmaple** [comment]
@bumaociyuan  good 我这个是个人开发者证书，如果在安装证书的时候能获取udid自动添加到证书里就好了

**Comment by bumaociyuan** [comment]
@phpmaple fir能自动获取，但是还是需要你手动添加， http://fir.im/udid
