### ISSUE TITLE
ipa可正常传输，但提示无法安装请稍后再试

### ISSUE THREAD

**Issue by thekips** [bumaociyuan/ios-ipa-server#55]
iOS版本：16.0
提示：无法安装请稍后再试

使用`node --trace-warnings`打印错误如下：
```
Open download page https://192.168.1.5:1234/download
(node:21464) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/cd.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/chmod.js:32:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/cp.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/dirs.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/dirs.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/dirs.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/echo.js:3:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/tempdir.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/pwd.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/exec.js:10:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/ls.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/find.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/grep.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/head.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/ln.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/mkdir.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/rm.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/mv.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/sed.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/set.js:3:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/sort.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/tail.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/test.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/to.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/toEnd.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)     at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)        at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/touch.js:4:8)                                                             at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/uniq.js:13:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
(node:21464) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:755:11)
    at Object.get (node:internal/modules/cjs/loader:771:5)
    at Object._register [as register] (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/ios-ipa-server/node_modules/shelljs/src/which.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
```

安装界面如下：

![无法安装提示](https://cdn.jsdelivr.net/gh/thekips/PicGo/Notes/IMG_0493.PNG)

**Comment by mengqutaoyuan** [comment]
同样的问题，怀疑plist 文件问题
